# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kestrel < Formula
  desc "Command-line interface for the Kestrel Portfolio API"
  homepage "https://kestrelportfolio.com"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kestrelportfolio/cli/releases/download/v0.4.0/kestrel_0.4.0_darwin_amd64.tar.gz"
      sha256 "e0ab5c802cf06bfc950058f52141caeee2d4a989effec7048924ec34f0ebc5d6"

      define_method(:install) do
        bin.install "kestrel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kestrelportfolio/cli/releases/download/v0.4.0/kestrel_0.4.0_darwin_arm64.tar.gz"
      sha256 "0bf7ba696f2f5b351fb5748cfc4a74be95a4012c68b61c714bb32dc9fee5f156"

      define_method(:install) do
        bin.install "kestrel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kestrelportfolio/cli/releases/download/v0.4.0/kestrel_0.4.0_linux_amd64.tar.gz"
      sha256 "1c67cb898edc0cc3e1eac9a09b0fe46c9e2bc194e2f3c0bbfdb26076f2379933"
      define_method(:install) do
        bin.install "kestrel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kestrelportfolio/cli/releases/download/v0.4.0/kestrel_0.4.0_linux_arm64.tar.gz"
      sha256 "3f8025e2a0b792534dd84e5b6637b7ca52e01362e66a9a8845f9a5868b195065"
      define_method(:install) do
        bin.install "kestrel"
      end
    end
  end
end
