# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kestrel < Formula
  desc "Command-line interface for the Kestrel Portfolio API"
  homepage "https://kestrelportfolio.com"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kestrelportfolio/cli/releases/download/v0.3.2/kestrel_0.3.2_darwin_amd64.tar.gz"
      sha256 "b79cd1f500307c05a2b3ebcd50778259017d10395db98439da7712f7345e347b"

      define_method(:install) do
        bin.install "kestrel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kestrelportfolio/cli/releases/download/v0.3.2/kestrel_0.3.2_darwin_arm64.tar.gz"
      sha256 "c31073520f5b67980f2b53737f889412af98aecf17117fa2a0021e452b26a7bd"

      define_method(:install) do
        bin.install "kestrel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kestrelportfolio/cli/releases/download/v0.3.2/kestrel_0.3.2_linux_amd64.tar.gz"
      sha256 "6b0fdde74bd3a936aada356e9b4e6d4407c95cd9feec248977f99a394c7e8818"
      define_method(:install) do
        bin.install "kestrel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kestrelportfolio/cli/releases/download/v0.3.2/kestrel_0.3.2_linux_arm64.tar.gz"
      sha256 "8f688d7ab5c2d8443456870cdf46f24a579be1276eef6a8908e5fd48665db66d"
      define_method(:install) do
        bin.install "kestrel"
      end
    end
  end
end
